version: "3"

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped

volumes:
  syncthing:
